tinyMCE.addI18n('zh_tw.big5.advanced',{
style_select:"樣式",
font_size:"文字大小",
fontdefault:"字型",
block:"格式",
paragraph:"段落",
div:"層級",
address:"地址",
pre:"預設格式",
h1:"標題 1",
h2:"標題 2",
h3:"標題 3",
h4:"標題 4",
h5:"標題 5",
h6:"標題 6",
blockquote:"引用",
code:"代碼",
samp:"代碼範例",
dt:"名詞定義",
dd:"名詞描述",
bold_desc:"粗體（Ctrl+B）",
italic_desc:"斜體（Ctrl+I）",
underline_desc:"底線（Ctrl+U）",
striketrough_desc:"刪除線",
justifyleft_desc:"靠左對齊",
justifycenter_desc:"置中對齊",
justifyright_desc:"靠右對齊",
justifyfull_desc:"左右對齊",
bullist_desc:"項目列表",
numlist_desc:"編號列表",
outdent_desc:"減少縮排",
indent_desc:"增加縮排",
undo_desc:"復原（Ctrl+Z）",
redo_desc:"取消復原（Ctrl+Y）",
link_desc:"插入/編輯連結",
unlink_desc:"刪除連結",
image_desc:"插入/編輯圖片",
cleanup_desc:"清除格式",
code_desc:"編輯 HTML 原始碼",
sub_desc:"下標",
sup_desc:"上標",
hr_desc:"水平線",
removeformat_desc:"清除格式",
custom1_desc:"請輸入描述",
forecolor_desc:"選擇文字顏色",
backcolor_desc:"選擇背景顏色",
charmap_desc:"插入特殊符號",
visualaid_desc:"顯示/隱藏元素",
anchor_desc:"插入/編輯書籤",
cut_desc:"剪貼",
copy_desc:"複製",
paste_desc:"貼上",
image_props_desc:"圖片屬性",
newdocument_desc:"新文件",
help_desc:"說明",
blockquote_desc:"引用",
clipboard_msg:"很抱歉，您的瀏覽器不支援複製/剪貼功能！",
path:"路徑",
newdocument:"您確定要清除所有的內容嗎？",
toolbar_focus:"Alt+X：到工具列、Alt+Q：到編輯框、Alt+Z：到元素路徑",
more_colors:"更多顏色"
});
