tinyMCE.addI18n({'zh_tw.big5':{
common:{
edit_confirm:"是否要開啟文字編輯器？",
apply:"套用",
insert:"插入",
update:"更新",
cancel:"取消",
close:"關閉",
browse:"瀏覽",
class_name:"類別",
not_set:"-- 尚未設定 --",
clipboard_msg:"很抱歉，您的瀏覽器不支援複製/剪貼功能！",
clipboard_no_support:"您的瀏覽器不支援此項功能，請使用 [Ctrl+C] 代替。",
popup_blocked:"您的瀏覽器攔截了彈出視窗！",
invalid_data:"您輸入的資料有誤（紅色標示）！",
more_colors:"更多顏色"
},
contextmenu:{
align:"對齊方式",
left:"靠左對齊",
center:"置中",
right:"靠右對齊",
full:"左右對齊"
},
insertdatetime:{
date_fmt:"%Y-%m-%d",
time_fmt:"%H:%M:%S",
insertdate_desc:"插入目前日期",
inserttime_desc:"插入目前時間",
months_long:"一月,二月,三月,四月,五月,六月,七月,八月,九月,十月,十一月,十二月",
months_short:"1月,2月,3月,4月,5月,6月,7月,8月,9月,10月,11月,12月",
day_long:"星期日,星期一,星期二,星期三,星期四,星期五,星期六,星期日",
day_short:"週日,週一,週二,週三,週四,週五,週六,週日"
},
print:{
print_desc:"列印"
},
preview:{
preview_desc:"預覽列印"
},
directionality:{
ltr_desc:"由左至右",
rtl_desc:"由右至左"
},
layer:{
insertlayer_desc:"插入圖層",
forward_desc:"向前",
backward_desc:"向後",
absolute_desc:"絕對位置",
content:"新圖層..."
},
save:{
save_desc:"儲存",
cancel_desc:"取消所有變更"
},
nonbreaking:{
nonbreaking_desc:"插入空格"
},
iespell:{
iespell_desc:"拼寫檢查",
download:"未發現 ieSpell 套件，是否立即安裝？"
},
advhr:{
advhr_desc:"水平線"
},
emotions:{
emotions_desc:"表情"
},
searchreplace:{
search_desc:"搜尋",
replace_desc:"搜尋/取代"
},
advimage:{
image_desc:"插入/編輯圖片"
},
advlink:{
link_desc:"插入/編輯連結"
},
xhtmlxtras:{
cite_desc:"引用",
abbr_desc:"縮寫",
acronym_desc:"第一個字母縮寫",
del_desc:"刪除",
ins_desc:"插入",
attribs_desc:"插入/編輯屬性"
},
style:{
desc:"編輯 CSS 樣式"
},
paste:{
paste_text_desc:"貼上純文字",
paste_word_desc:"從 Word 貼上文字",
selectall_desc:"全選",
plaintext_mode_sticky:"目前為純文字剪貼模式，請再點選一次切換回一般模式。",
plaintext_mode:"目前為一般剪貼模式，請再點選一次切換回純文字模式。"
},
paste_dlg:{
text_title:"使用 [Ctrl+V] 貼上內容",
text_linebreaks:"保留分行符號",
word_title:"使用 [Ctrl+V] 貼上內容"
},
table:{
desc:"插入新表格",
row_before_desc:"在上方插入一行",
row_after_desc:"在下方插入一行",
delete_row_desc:"刪除所在的行",
col_before_desc:"在左方插入一欄",
col_after_desc:"在右方插入一欄",
delete_col_desc:"刪除所在的欄",
split_cells_desc:"分割儲存格",
merge_cells_desc:"合併儲存格",
row_desc:"行的屬性",
cell_desc:"儲存格的屬性",
props_desc:"表格的屬性",
paste_row_before_desc:"在上方貼上表格的行",
paste_row_after_desc:"在下方貼上表格的行",
cut_row_desc:"剪下表格的行",
copy_row_desc:"複製表格的行",
del:"刪除表格",
row:"行",
col:"欄",
cell:"儲存格"
},
autosave:{
unload_msg:"您所輸入的內容尚未儲存，可能會遺失...",
restore_content:"恢復自動儲存的內容",
warning_message:"如果恢復先前儲存的內容，您將會失去目前所編輯的內容。\n\n您確定要恢復先前所儲存的內容嗎？"
},
fullscreen:{
desc:"全螢幕模式"
},
media:{
desc:"插入/編輯影片",
edit:"編輯影片"
},
fullpage:{
desc:"文件屬性"
},
template:{
desc:"插入預設的樣版內容"
},
visualchars:{
desc:"顯示/隱藏編輯標記"
},
spellchecker:{
desc:"開/關拼寫檢查",
menu:"拼寫檢查設定",
ignore_word:"忽略",
ignore_words:"忽略全部",
langs:"語言",
wait:"請稍候...",
sug:"建議",
no_sug:"無建議",
no_mpell:"無拼寫錯誤"
},
pagebreak:{
desc:"插入分頁符號"
},
advlist:{
types:"樣式",
def:"預設",
lower_alpha:"小寫的英文",
lower_greek:"小寫的希臘文",
lower_roman:"小寫的羅馬文",
upper_alpha:"大寫的英文",
upper_roman:"大寫的羅馬文",
circle:"圓圈",
disc:"圓點",
square:"方形"
},
loxamail:{
unload_msg:"如果離開這個畫面，您將會失去目前所編輯的內容。"
}}});
