tinyMCE.addI18n('zh_tw.big5.simple',{
bold_desc:"粗體（Ctrl+B）",
italic_desc:"斜體（Ctrl+I）",
underline_desc:"底線（Ctrl+U）",
striketrough_desc:"刪除線",
bullist_desc:"項目列表",
numlist_desc:"編號列表",
undo_desc:"復原（Ctrl+Z）",
redo_desc:"取消復原（Ctrl+Y）",
cleanup_desc:"清除格式"
});
